name: 08 - Using Variables
on:
  workflow_dispatch:
env:
  WORKFLOW_VAR: "WORKFLOW VAR"
  OVERWRITTEN: "OVERWRITTEN WORKFLOW VAR"
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "JOB VAR"
      OVERWRITTEN: "OVERWRITTEN JOB VAR"
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: "STEP VAR"
          STEP_VAR2: "step var 2"
        run: |
          echo "Step env var: ${{env.STEP_VAR}}"
          echo "Step env var 2: ${{env.STEP_VAR2}}"
          echo "Job env var: ${{env.JOB_VAR}}"
          echo "Workflow env var: ${{env.WORKFLOW_VAR}}"
          echo "Overwritten: ${{env.OVERWRITTEN}}"
      - name: Overwrite Job Variable
        env:
          OVERWRITTEN: "I have been overwritten at the step level"
        run: |
          echo "Step env var: ${{env.OVERWRITTEN}}"
