name: 13 - Using Caching
on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: "Whether to execute cache step"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "04-using-actions/my-posta"
    steps:
      - name: Checkout code
        uses: actions/Checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Cache node module
        id: cache-node-module
        uses: actions/cache@v3
        with:
          path: "04-using-actions/my-posta/node_modules"
          key: deps-${{hashFiles('04-using-actions/my-posta/package-lock.json')}}
      - name: Install dependencies
        if: ${{steps.cache-node-module.outputs.cache-hit != 'true'}}
        run: npm ci
      - name: linting
        run: npm run lint
      - name: Building
        run: npm run build
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"
