name: 14 - Working with Artifacts
on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/my-posta
    steps:
      - name: Checkout code
        uses: actions/Checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: 04-using-actions/my-posta/node_modules
          key: deps-node-modules-${{ hashFiles('04-using-actions/my-posta/package-lock.json') }}

      - name: Install dependencies
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build code
        run: npm run build

      - name: List directory
        run: ls

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: 04-using-actions/my-posta/.next

  deploy:
    runs-on: ubuntu-latest
    needs: [test-build]
    steps:
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: app
          path: build
